### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by kai3341**

### CODE REVIEW

**Comment by kai3341** [comment]
@auvipy I almost finished API implementation, but it looks i've done many stupid architecture mistakes. I need your total review, then i'll refactor code as you tell, and then open new PR with this pool into celery mainstream

**Comment by auvipy** [comment]
thanks, Anton, I will review it tomorrow :)

**Review by Jagrmi-C — APPROVED** [review]

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
may I know what inputs you are looking from me? any context will be helpful

**Comment by kai3341** [comment]
@auvipy I'm talking about whole `celery-pool-asyncio` project. For example, I see methods `get_event_loop`, `register_with_event_loop`. I found them too much after I implemented creating event loop inside own thread. So, my code is sure smelling. This is main problem, but i think it's not the only.

I don't know how to write personal message here. That's why i wrote here, and I use this PR as communication platform. Maybe you have better idea. Is it better to create an issue?

**Comment by auvipy** [comment]
cool. i will surely check it fully. we can start an issue

**Pull request merged**
