### PR TITLE
Add task revoke support

### PR DESCRIPTION
**Pull request by kai3341**
Created running task registry

### CODE REVIEW

**Comment by povilasb** [comment]
Uu, this is definitely something I'm interested in :)
Are the changes complete?

**Comment by kai3341** [comment]
@povilasb almost. Hm, it's good idea to finalize this PR

**Comment by kai3341** [comment]
@povilasb finished. Then review, then merge, then upload to pypi

**Review by Jagrmi-C — APPROVED** [review]

**Comment by kai3341** [comment]
@povilasb merged, available at pypi

**Review by liferea — COMMENTED** [review]
.

**Comment by povilasb** [comment]
Awesome, thanks for your work :)

**Pull request merged**
